sudo: required
dist: trusty
language: ruby

before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: knC942xqGurV24l2TdUBIPQ7W+FWmWEOuAyvBQ3TdQcyhw3ZxhNVHNAmKOi12DoGAmnDJ+sp6GxO0mOr8sEbYpWRu/jpPp3HKYY9wCX09swfU17dRcf/6a7e5DZPnFyFWqZo45iHgy0GuABzeHiiyZJT41RJAZWtjS1HAubMa7pNn2tVT2GLqMO3mglAuQld5jYrMS1zZ64/7FKbkxhtaL4CI666bB6uHaE80aXiRGJPwZcjTdO12bcGvydNDM5k4fwkiDAbCdffEJvwUQKYYA6scxzOFlwrtc3Zw4/uBPXITaCvtgagxrhmhPW16cclM9vW2ngqEzTos9nPQbXQqA5rAyu59FteM4pjqE+wHGLfrNjzXX98dTXkzv+W4N2msU87QdrA6+IStGoKwpLT3hx6m2PjEDawLnwWwb4136ptWPKD24Fpe8CkQzi6T0qoL1nVsH7F6vN9mDATLPyzmmTc/errFI1san4BAHBtHITqU8+bHUrDxDZ3xGTNHooodcckQPRxrhSGUPDv/I17HDVWDokVfisGVSpL3PwDw4lgfWdqdFm19xFXF5EMhoF66OkjPidrTb0ZfEAa2gS86WEWi1w4UlEEyHdnO7Kj/vCxYr828aGs61o9UMa8dCrhGVaL9rW0b4WEMo5D/5IOc3t4NNuqp1yg+o8+sXPWigs=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  on:
    repo: GITenberg/Stories-by-English-Authors--The-Orient--Selected-by-Scribners-_2035
    tags: true
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy